services:
  bot:
    image: ghcr.io/raphtlw/raphgpt:latest
    restart: always
    volumes:
      - appdata:${DATA_DIR}
    env_file:
      - .env

  python:
    image: ghcr.io/raphtlw/raphgpt-python:latest
    restart: always
    volumes:
      - appdata:${DATA_DIR}
    environment:
      - DATA_DIR=${DATA_DIR}
      - INFISICAL_TOKEN=${INFISICAL_TOKEN}

  postgres:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis
    restart: always
    ports:
      - 6379:6379
    volumes:
      - redisdata:/data
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    command: redis-server --save 60 1 --loglevel warning

  gotenberg:
    image: gotenberg/gotenberg:8
    ports:
      - "60463:3000"

volumes:
  appdata:
  pgdata:
  redisdata:
