services:
  bot:
    image: ghcr.io/raphtlw/raphgpt:latest
    restart: always
    volumes:
      - appdata:${DATA_DIR}
    env_file:
      - .env
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  python:
    image: ghcr.io/raphtlw/raphgpt-python:latest
    restart: always
    volumes:
      - appdata:${DATA_DIR}
    env_file:
      - .env
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  postgres:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis
    restart: always
    ports:
      - 6379:6379
    volumes:
      - redisdata:/data
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    command: redis-server --save 60 1 --loglevel warning

  gotenberg:
    image: gotenberg/gotenberg:8
    ports:
      - "60463:3000"

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --debug --http-api-update --label-enable
    environment:
      - WATCHTOWER_HTTP_API_TOKEN=${WATCHTOWER_HTTP_API_TOKEN}
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    ports:
      - 8084:8080

volumes:
  appdata:
  pgdata:
  redisdata:
