services:
  bot:
    image: ghcr.io/raphtlw/raphgpt:latest
    restart: always
    volumes:
      - appdata:${DATA_DIR}
    environment:
      - NODE_ENV=${NODE_ENV}
      - PYTHON_URL=${PYTHON_URL}
      - INFISICAL_TOKEN=${INFISICAL_TOKEN}
      - DATA_DIR=${DATA_DIR}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - CHROMA_BACKEND_URL=${CHROMA_BACKEND_URL}
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  python:
    image: ghcr.io/raphtlw/raphgpt-python:latest
    restart: always
    volumes:
      - appdata:${DATA_DIR}
    environment:
      - NODE_ENV=${NODE_ENV}
      - PYTHON_URL=${PYTHON_URL}
      - INFISICAL_TOKEN=${INFISICAL_TOKEN}
      - DATA_DIR=${DATA_DIR}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - CHROMA_BACKEND_URL=${CHROMA_BACKEND_URL}
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  postgres:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis
    restart: always
    ports:
      - 6379:6379
    volumes:
      - redisdata:/data
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    command: redis-server --save 60 1 --loglevel warning

  chroma:
    image: chromadb/chroma
    restart: always
    ports:
      - 29920:8000

  gotenberg:
    image: gotenberg/gotenberg:8
    restart: always
    ports:
      - 60463:3000

volumes:
  appdata:
  pgdata:
  redisdata:
