services:
  telegram-bot:
    image: ghcr.io/raphtlw/raphgpt-telegram-bot:main
    build: ./telegram-bot
    develop:
      watch:
        - path: ./telegram-bot
          action: sync+restart
          target: /app
          ignore:
            - node_modules/
        - path: ./telegram-bot/package.json
          action: rebuild
    env_file: .env
    restart: unless-stopped

  video-parser:
    image: ghcr.io/raphtlw/raphgpt-video-parser:main
    platform: linux/amd64
    build: ./video-parser
    develop:
      watch:
        - path: ./video-parser
          action: sync+restart
          target: /app
          ignore:
            - .venv/
        - path: ./video-parser/pyproject.toml
          action: rebuild
    env_file: .env
    restart: unless-stopped

  task-queue:
    image: ghcr.io/raphtlw/raphgpt-task-queue:main
    build: ./task-queue
    command: fastapi run app/main.py --port 80 --host 0.0.0.0
    develop:
      watch:
        - path: ./task-queue
          action: sync+restart
          target: /app
          ignore:
            - .venv/
        - path: ./task-queue/pyproject.toml
          action: rebuild
    env_file: .env
    restart: unless-stopped

  task-queue-worker:
    image: ghcr.io/raphtlw/raphgpt-task-queue:main
    build: ./task-queue
    command: uv run app/worker.py
    develop:
      watch:
        - path: ./task-queue
          action: sync+restart
          target: /app
          ignore:
            - .venv/
        - path: ./task-queue/pyproject.toml
          action: rebuild
    env_file: .env
    restart: unless-stopped

  browserless:
    image: ghcr.io/browserless/chromium
    environment:
      - DEBUG=-*
    restart: unless-stopped

  gotenberg:
    image: gotenberg/gotenberg:8
    restart: unless-stopped
