services:
  bot:
    image: ghcr.io/raphtlw/raphgpt:latest
    restart: always
    volumes:
      - appdata:${DATA_DIR}
    env_file:
      - path: stack.env
        required: false
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  redis:
    image: redis
    restart: always
    ports:
      - 6379:6379
    volumes:
      - redisdata:/data
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    command: redis-server --save 60 1 --loglevel warning

  gotenberg:
    image: gotenberg/gotenberg:8
    restart: always
    ports:
      - ${GOTENBERG_PORT}:3000

  chromadb:
    image: chromadb/chroma
    restart: always
    ports:
      - ${CHROMA_PORT}:8000

volumes:
  appdata:
  redisdata:
