import { ThemeProvider } from "@/components/provider/theme";
import { ModeToggle } from "@/components/ui/mode-toggle";
import clsx from "clsx";
import type { Metadata } from "next";
import { JetBrains_Mono, Syne } from "next/font/google";
import "./globals.css";

const syne = Syne({ subsets: ["latin"], variable: "--font-syne" });
const jetbrains = JetBrains_Mono({
  subsets: ["latin"],
  variable: "--font-jetbrains",
});

export const metadata: Metadata = {
  title: "raphGPT",
  description: "View markdown files generated by the bot",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang='en'
      className={clsx(syne.variable, jetbrains.variable)}
      suppressHydrationWarning
    >
      <body className='dark:bg-[#161a1d]'>
        <ThemeProvider
          attribute='class'
          defaultTheme='system'
          enableSystem
          disableTransitionOnChange
        >
          <header
            className={clsx(
              "sticky top-0 z-20 flex items-center px-4 py-2",
              "filter backdrop-blur",
              "border-b-[0.37px] border-b-slate-400 dark:border-b-slate-700",
              "bg-slate-200 bg-opacity-10",
              "dark:bg-zinc-800 dark:bg-opacity-10"
            )}
          >
            <div className='flex flex-col'>
              <p className='font-light'>{metadata.title?.toString()}</p>
              <p className='text-xl'>{metadata.description?.toString()}</p>
            </div>
            <div className='flex-1'></div>
            <ModeToggle />
          </header>
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
