[project]
name = "task-queue"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi[all]>=0.115.13",
    "python-telegram-bot>=22.1",
    "redis>=6.2.0",
    "telegramify-markdown>=0.5.1",
]
