import { getEnv } from "@/helpers/env.js";
import os from "os";
import path from "path";

export const DATA_DIR =
  getEnv("NODE_ENV") === "production"
    ? path.resolve("/raphgpt-data")
    : path.join(os.homedir(), ".local", "share", "raphgpt");
export const LOCAL_FILES_DIR = path.join(DATA_DIR, "files");
export const BROWSER_FILES_DIR = path.join(DATA_DIR, "browser");

export const PROMPTS_DIR = path.join(process.cwd(), "prompts");

export const PRODUCTION = getEnv("NODE_ENV") === "production";

export const OPENROUTER_FREE = "deepseek/deepseek-r1:free";

export const TYPING_INDICATOR_DURATION = 5 * 1000;

export const WHISPER_LANGUAGES = [
  "None",
  "afrikaans",
  "albanian",
  "amharic",
  "arabic",
  "armenian",
  "assamese",
  "azerbaijani",
  "bashkir",
  "basque",
  "belarusian",
  "bengali",
  "bosnian",
  "breton",
  "bulgarian",
  "cantonese",
  "catalan",
  "chinese",
  "croatian",
  "czech",
  "danish",
  "dutch",
  "english",
  "estonian",
  "faroese",
  "finnish",
  "french",
  "galician",
  "georgian",
  "german",
  "greek",
  "gujarati",
  "haitian creole",
  "hausa",
  "hawaiian",
  "hebrew",
  "hindi",
  "hungarian",
  "icelandic",
  "indonesian",
  "italian",
  "japanese",
  "javanese",
  "kannada",
  "kazakh",
  "khmer",
  "korean",
  "lao",
  "latin",
  "latvian",
  "lingala",
  "lithuanian",
  "luxembourgish",
  "macedonian",
  "malagasy",
  "malay",
  "malayalam",
  "maltese",
  "maori",
  "marathi",
  "mongolian",
  "myanmar",
  "nepali",
  "norwegian",
  "nynorsk",
  "occitan",
  "pashto",
  "persian",
  "polish",
  "portuguese",
  "punjabi",
  "romanian",
  "russian",
  "sanskrit",
  "serbian",
  "shona",
  "sindhi",
  "sinhala",
  "slovak",
  "slovenian",
  "somali",
  "spanish",
  "sundanese",
  "swahili",
  "swedish",
  "tagalog",
  "tajik",
  "tamil",
  "tatar",
  "telugu",
  "thai",
  "tibetan",
  "turkish",
  "turkmen",
  "ukrainian",
  "urdu",
  "uzbek",
  "vietnamese",
  "welsh",
  "yiddish",
  "yoruba",
] as const;
