name: "Build and Publish"

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  deploy:
    name: Deploy Telegram Bot Service
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push container image
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ghcr.io/raphtlw/raphgpt:latest
          cache-from: type=registry,ref=ghcr.io/raphtlw/raphgpt:buildcache
          cache-to: type=registry,ref=ghcr.io/raphtlw/raphgpt:buildcache,mode=max
