name: "Build and Publish"

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  deploy:
    strategy:
      matrix:
        service: [bot, python]
    name: Deploy Telegram Bot Service
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: Build and push bot image
        if: matrix.service == 'bot'
        uses: docker/build-push-action@v6
        with:
          context: ./bot
          push: true
          tags: ghcr.io/raphtlw/raphgpt:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Build and push python image
        if: matrix.service == 'python'
        uses: docker/build-push-action@v6
        with:
          context: ./python
          push: true
          tags: ghcr.io/raphtlw/raphgpt-python:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Trigger container update
        env:
          TOKEN: ${{ secrets.WATCHTOWER_HTTP_API_TOKEN }}
        run: |
          curl -H "Authorization: Bearer $TOKEN" https://raphgpt-trigger-update.raphtlw.com/v1/update
